name: resolve-DoH-elf-hosts-and-save-ipcidr

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["separate-host-from-list"]  # Name of the first workflow
    types:
      - completed

jobs:
  resolve-DoH-elf-hosts-and-save-ipcidr:
    runs-on: ubuntu-latest

    env:
      RESOLVERS: "223.5.5.5 119.29.29.29"  # List of resolvers as space-separated values
      INPUT: "DoH-elf.list"
      HOSTLIST: "host-list.txt"
      IPCIDRLIST_V4: "ipcidr-list-v4.txt"
      IPCIDRLIST_V6: "ipcidr-list-v6.txt"
      OUTPUT_V4: "${{ github.workspace }}/ipcidr/DoH-elf-ipcidr-v4.txt"
      OUTPUT_V6: "${{ github.workspace }}/ipcidr/DoH-elf-ipcidr-v6.txt"
      
    steps:
      - uses: actions/checkout@v3  # Checkout the repo

      - name: Extract hostnames and IP-CIDRs
        run: |
          mkdir -p $(dirname "$OUTPUT_V4")
          mkdir -p $(dirname "$OUTPUT_V6")
          
          # Create empty files for hostnames and IP-CIDRs
          > $HOSTLIST
          > $IPCIDRLIST_V4
          > $IPCIDRLIST_V6
          
          # Process each line from the input file
          grep -iE '^HOST,|^DOMAIN,|^IP-CIDR,|^IP-CIDR6,|^IP6-CIDR,' $INPUT | while IFS=',' read -r type value other; do
            if [[ "$type" == "HOST" ]] || [[ "$type" == "DOMAIN" ]]; then
              # Save HOST directly to the file
              echo "$value" >> $HOSTLIST
              echo "Saved HOST: $value"
            elif [[ "$type" == "IP-CIDR" ]]; then
              # Save IP-CIDR directly to the IPv4 file
              echo "$value" >> $IPCIDRLIST_V4
              echo "Saved IP-CIDR: $value"
            elif [[ "$type" == "IP-CIDR6" ]] || [[ "$type" == "IP6-CIDR" ]]; then
              # Save IP-CIDR directly to the IPv6 file
              echo "$value" >> $IPCIDRLIST_V6
              echo "Saved IP-CIDR6: $value"
            fi
          done

      - name: Resolve DNS with dig using resolvers list (handling resolution errors)
        run: |
          echo "Resolving domains using dig with resolvers $RESOLVERS..."
          > resolved_ips_v4.txt  # Create an empty file for IPv4 results
          > resolved_ips_v6.txt  # Create an empty file for IPv6 results

          # Convert resolvers to an array (space-separated list)
          IFS=' ' read -r -a resolver_array <<< "$RESOLVERS"

          # Read domains from host-list.txt and resolve them using each resolver
          while IFS= read -r domain; do
            echo "Resolving $domain with resolvers ${resolver_array[@]}..."
            
            # Resolve IPv4 addresses
            for resolver in "${resolver_array[@]}"; do
              echo "Resolving $domain using resolver $resolver"
              result=$(dig @$resolver +subnet=114.114.114.114/24 +short $domain +time=5 +retry=3 || true)
            
              echo "Result:"
              echo $result
            
              if [[ -z "$result" ]]; then
                echo "No IPv4 addresses found for $domain using resolver $resolver"
              else
                # Loop through each result (in case multiple addresses are returned)
                for ip in $result; do
                  # Check if the result is an IP address (IPv4 format)
                  if [[ "$ip" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                    # If it's an IPv4 address, just append it
                    echo "$ip" >> resolved_ips_v4.txt
                    echo "Found IPv4 address: $ip"
                  else
                    # If it's not an IP address, assume it's a CNAME and resolve further
                    cname_result=$(dig @$resolver +subnet=114.114.114.114/24 +short $ip +time=5 +retry=3 || true)
                    if [[ -n "$cname_result" ]]; then
                      # If CNAME resolved to IPv4, append those to resolved_ips_v4.txt
                      for cname_ip in $cname_result; do
                        if [[ "$cname_ip" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                          echo "$cname_ip" >> resolved_ips_v4.txt
                          echo "Found IPv4 address for CNAME $ip: $cname_ip"
                        fi
                      done
                    else
                      echo "No IPv4 addresses found for CNAME $ip using resolver $resolver"
                    fi
                  fi
                done
              fi
            done

            # Similarly for IPv6
            for resolver in "${resolver_array[@]}"; do
              echo "Resolving $domain using resolver $resolver"
              result=$(dig @$resolver +subnet=240e:382:1c:9100::/56 +short -t AAAA $domain +time=5 +retry=3 || true)
            
              echo "Result:"
              echo $result
            
              if [[ -z "$result" ]]; then
                echo "No IPv6 addresses found for $domain using resolver $resolver"
              else
                # Loop through each result (in case multiple addresses are returned)
                for ip in $result; do
                  # Check if the result is an IPv6 address
                  if [[ "$ip" =~ ^[0-9a-fA-F:]+$ ]]; then
                    # If it's an IPv6 address, just append it
                    echo "$ip" >> resolved_ips_v6.txt
                    echo "Found IPv6 address: $ip"
                  else
                    # If it's not an IP address, assume it's a CNAME and resolve further
                    cname_result=$(dig @$resolver +subnet=240e:382:1c:9100::/56 +short -t AAAA $ip +time=5 +retry=3 || true)
                    if [[ -n "$cname_result" ]]; then
                      # If CNAME resolved to IPv6, append those to resolved_ips_v6.txt
                      for cname_ip in $cname_result; do
                        if [[ "$cname_ip" =~ ^[0-9a-fA-F:]+$ ]]; then
                          echo "$cname_ip" >> resolved_ips_v6.txt
                          echo "Found IPv6 address for CNAME $ip: $cname_ip"
                        fi
                      done
                    else
                      echo "No IPv6 addresses found for CNAME $ip using resolver $resolver"
                    fi
                  fi
                done
              fi
            done
          done < $HOSTLIST

          # Optionally log the final output for debugging
          # echo "Final resolved IPv4 addresses:"
          # cat resolved_ips_v4.txt
          # echo "Final resolved IPv6 addresses:"
          # cat resolved_ips_v6.txt

      - name: Process and extract IPs and CIDRs
        run: |
          echo "Processing resolved IPs and extracting CIDRs"
          
          # Append resolved IPs to the respective IP-CIDR lists
          cat resolved_ips_v4.txt >> $IPCIDRLIST_V4
          cat resolved_ips_v6.txt >> $IPCIDRLIST_V6

          # Append original IP-CIDR list to output
          cat $IPCIDRLIST_V4 >> $OUTPUT_V4
          cat $IPCIDRLIST_V6 >> $OUTPUT_V6

          # Remove duplicates and sort the final list of IPs and CIDRs
          sort -u $OUTPUT_V4 -o $OUTPUT_V4  # Sort and remove duplicates in place for IPv4
          sort -u $OUTPUT_V6 -o $OUTPUT_V6  # Sort and remove duplicates in place for IPv6

          # Display the final result
          echo "IPv4 CIDRs:"
          cat $OUTPUT_V4
          echo "IPv6 CIDRs:"
          cat $OUTPUT_V6
          
      - name: Commit and push the changes
        run: |
          # Configure git with your name and email (use the GitHub Actions bot credentials)
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Stage the output files
          git add $OUTPUT_V4 $OUTPUT_V6
          
          # Check if there are changes to commit
          if ! git diff --staged --quiet; then
            # Commit and push if there are changes
            git commit -m "resolve host to ip in DoH-elf.list and save ipcidr"
            git push origin main
          else
            echo "No changes detected, skipping commit and push."
          fi
