name: Resolve

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  resolve-hosts-and-save-ipcidr:
    runs-on: ubuntu-latest

    env:
      RESOLVER1: "223.5.5.5"
      RESOLVER2: "119.29.29.29"
      INPUT: "DoH-elf.list"
      OUTPUT: "ipcidr.txt"
      
    steps:
      - uses: actions/checkout@v3  # Checkout the repo

      - name: Use dnsx to resolve domains
        uses: projectdiscovery/dnsx-action@v1
        with:
          input: ${{ github.workspace }}/$INPUT  # Path to input file with domains
          resolvers: "$RESOLVER1,$RESOLVER2"  # Your resolvers
          output: ${{ github.workspace }}/$OUTPUT  # Output file to save results

      - name: Process and extract IPs and CIDRs
        run: |
          echo "Processing resolved IPs and extracting CIDRs"
          
          # Remove duplicates and sort the final list of IPs and CIDRs
          sort -u $OUTPUT -o $OUTPUT  # Sort and remove duplicates in place
          cat $OUTPUT  # Display the final result
